version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(actions)"
    reviewers:
      - "ninepiece2"